[package]
name = "content-addressed-cache"
version = "0.7.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
git2 = { version = "0.15", features = [
  "vendored-libgit2",
  "vendored-openssl",
] }
focus-util = { path = "../focus/util" }
hex = "0.3.1"
lazy_static = "1.4.0"
rand = "0.6.3"
regex = "1.5.5"
rocksdb = "0.19.0"
tempfile = "3.2.0"
tracing = "0.1.32"

[dev-dependencies]
ciborium = "0.2.0"
maplit = "1.0.2"
