mod project;
mod selection;
pub use project::Project;
pub use selection::Selection;
mod data_paths;
use data_paths::DataPaths;
mod persisted_selection;
use persisted_selection::PersistedSelection;
mod selections;
pub use selections::Selections;
mod selection_operation_processor;
use selection_operation_processor::SelectionOperationProcessor;
mod operations;
pub use operations::Operation;
pub use operations::OperationAction;
pub use operations::OperationResult;
pub use operations::Underlying;
mod project_set;
pub use project_set::ProjectSet;
mod project_sets;
pub use project_sets::ProjectSets;
mod projects;
pub use projects::Projects;
#[cfg(test)]
mod testing;

pub use super::repo::Repo;
pub use super::repo::WorkingTree;
pub use crate::model::persistence::FileBackedCollection;
pub use crate::model::persistence::{load_model, store_model};
pub use crate::target::Target;
pub use crate::target::TargetError;
pub use crate::target::TargetSet;
