from pathlib import Path
from typing import ContextManager, Iterable, Optional, Tuple, Union

PathishT = Union[Path, str]

class FakeRefDb:
  def __init__(self,
    root: Optional[Path] = ...
  ) -> None: ...
  root: Path
  @classmethod
  def open(cls) -> ContextManager["FakeRefDb"]: ...
  def cleanup(self) -> None: ...
  def add_ref(self, ref: PathishT, orig_ref: str) -> None: ...
  def remove_r(self, ref: Path) -> None: ...
  def walk(self) -> Iterable[Tuple[str, str]]: ...

class FDNameConflict(OSError):
  ref: str
  filename: str
  conflict_ref: str
