# Copyright 2022 Twitter, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Linux

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.61.0
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@cb2cf0cc7c5198d3364b9630e2c3d457f160790c

      - name: Compile
        run: cargo build --features ci --all-targets --workspace

      # Don't test benches.
      - name: Run Rust tests
        timeout-minutes: 10
        run: cargo test --features ci --examples --tests --workspace

      # Note that `--doc` can't be combined with other tests.
      - name: Run Rust doc-tests
        timeout-minutes: 10
        run: cargo test --features ci --doc --workspace
